### ISSUE TITLE
Create FAQ Page

### ISSUE THREAD

**Issue by udara28** [chiphackers/zscore-wiki#11]
Add a accordian style FAQ Page to wiki.zscore.lk

- For questions like 
   - how to login using email or gmail
   - how to open a problem
   - how to clean workspace

**Comment by udara28** [comment]
@Lasitha64 were you able to get the accordion to work? In the FAQ can i request few more changes

- Replace the menu found in other pages like Contact.html. We need to change the index page menu to that menu as well. I will do it.
- The whole content is in "ui message" class which makes it darker and different from other pages. Let's make the background white as all other pages.
- The new menu has social media buttons so you can get rid of the floating sidebar menu with social accounts.
- Similar to other pages FAQ should also have a banner area. But I think we will have to come up with common banner style for all pages. For now keep a placeholder (a dummy spacing) where the cover should come.

Let me know how it goes. Good Luck

**Comment by Lasitha64** [comment]
I created the changes that you mentioned in FAQ page and I pull a request in GitHub please cheak.Thank you . Sent from Mail for Windows 10 From: Udara De SilvaSent: Friday, August 7, 2020 6:57 AMTo: chiphackers/zscore-wikiCc: Lasitha64; MentionSubject: Re: [chiphackers/zscore-wiki] Create FAQ Page (#11) @Lasitha64 were you able to get the accordion to work? In the FAQ can i request few more changesReplace the menu found in other pages like Contact.html. We need to change the index page menu to that menu as well. I will do it.The whole content is in "ui message" class which makes it darker and different from other pages. Let's make the background white as all other pages.The new menu has social media buttons so you can get rid of the floating sidebar menu with social accounts.Similar to other pages FAQ should also have a banner area. But I think we will have to come up with common banner style for all pages. For now keep a placeholder (a dummy spacing) where the cover should come.Let me know how it goes. Good Luck—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
